apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: {{ .Values.votingApp.serviceType }}
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.votingApp.containerPort }}
      nodePort: {{ .Values.votingApp.nodePort }}
